# fly.toml file generated for exposebot on 2022-12-05T20:07:56+11:00

app = "exposebot"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = "8080"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]

[deploy]
  strategy = "immediate"