# fly.toml app configuration file generated for exposebot on 2023-05-18T18:47:18+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "exposebot"
primary_region = "syd"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[deploy]
  strategy = "immediate"

[env]
  PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
